version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/conf/apache2/:/etc/apache2/sites-available/
    networks:
      - banana-api
    ports:
      - 80:80

  db:
    image: yobasystems/alpine-mariadb:10.4.17 #SPECIFIC IMAGE FOR ARM (RASPBERRY PI) ARCHITECTURE
    container_name: dbanana
    restart: always
    environment:
      MYSQL_DATABASE: banana
      MYSQL_USER: banana
      MYSQL_PASSWORD: banana
      MYSQL_ROOT_PASSWORD: banana
    ports: 
      - 3306:3306
    volumes:
      - persistent:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - banana-api

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - banana-api

networks:
  banana-api:
    driver: "bridge"

volumes:
  persistent:
