version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    # restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/conf/apache2/:/etc/apache2/sites-available/
    networks:
      - banana-api
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.5.6-focal
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banana
      MYSQL_DATABASE: banana
      MYSQL_USER: banana
      MYSQL_PASSWORD: banana
    volumes:
        - persistent:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - 3306:3306
    networks:
      - banana-api

  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080
    networks:
      - banana-api

networks:
  banana-api:
    driver: "bridge"

volumes:
  persistent:


