version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - ipms-api
    ports:
      - 80:80

networks:
  ipms-api:
    driver: "bridge"


