<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkIhw2a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkIhw2a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPkIhw2a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPkIhw2a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPkIhw2a\App_KernelDevDebugContainer([
    'container.build_hash' => 'PkIhw2a',
    'container.build_id' => '163976e3',
    'container.build_time' => 1618412909,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPkIhw2a');
