<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCOQXGpd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCOQXGpd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCOQXGpd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCOQXGpd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCOQXGpd\App_KernelDevDebugContainer([
    'container.build_hash' => 'COQXGpd',
    'container.build_id' => 'dd079ada',
    'container.build_time' => 1623845507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCOQXGpd');
